### ISSUE TITLE
Incorrect IP Address when checking bans

### ISSUE THREAD

**Issue by fuckoffjim** [grumpy-anonsaba/anonsaba-2.0#5]
Take a look at `post.php` lines 107 - 113:

The headers HTTP_CLIENT_IP and HTTP_X_FORWARDED_FOR (and others) are easy to spoof. Check out http://ipflood.paulds.fr/ for a browser plugin that abuses these headers.

tl;dr - You should be checking for REMOTE_ADDR first!

what the correct code should look like:

    if (!empty($_SERVER['REMOTE_ADDR'])) {
        $ipaddy = $_SERVER['REMOTE_ADDR'];
    } else if (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
        $ipaddy = $_SERVER['HTTP_X_FORWARDED_FOR'];
    } else {
        $ipaddy = $_SERVER['HTTP_CLIENT_IP'];
    }

I will make a thread on /bug/ demonstrating this.

**Comment by grumpy-anonsaba** [comment]
Fixed with 2a99a92... Thank you!
